/**
 * Strict HTML Sanitizer for Note-it
 * Whitelist allowed elements:
 * - <u> (Underline)
 * - <span data-note-it-color="#..." style="color:#...">
 * - <mark data-note-it-highlight="#..." style="background-color:#...">
 *
 * Removes dangerous tags (<script>, <iframe>, event handlers, javascript: URLs)
 */

const HEX_COLOR_REGEX = /^#([0-9A-Fa-f]{3}|[0-9A-Fa-f]{6})$/;

export function sanitizeHtml(rawHtml: string): string {
  if (!rawHtml) return '';

  // Use DOMParser in the browser/webview environment
  const parser = new DOMParser();
  const doc = parser.parseFromString(rawHtml, 'text/html');

  function sanitizeNode(node: Node): Node | null {
    if (node.nodeType === Node.TEXT_NODE) {
      return node;
    }

    if (node.nodeType === Node.ELEMENT_NODE) {
      const el = node as HTMLElement;
      const tagName = el.tagName.toLowerCase();

      // Block dangerous tags outright
      if (['script', 'iframe', 'object', 'embed', 'style', 'form', 'input', 'button'].includes(tagName)) {
        return null;
      }

      // Allowed safe standard formatting tags generated by markdown
      const allowedTags = new Set([
        'p', 'h1', 'h2', 'h3', 'h4', 'h5', 'h6',
        'strong', 'b', 'em', 'i', 'u', 's', 'strike',
        'ul', 'ol', 'li', 'blockquote', 'code', 'pre',
        'hr', 'br', 'a', 'span', 'mark'
      ]);

      if (!allowedTags.has(tagName)) {
        // Strip tag, keep children
        const fragment = document.createDocumentFragment();
        for (const child of Array.from(el.childNodes)) {
          const cleanChild = sanitizeNode(child);
          if (cleanChild) fragment.appendChild(cleanChild);
        }
        return fragment;
      }

      // Sanitize attributes
      const cleanEl = document.createElement(tagName);

      if (tagName === 'a') {
        const href = el.getAttribute('href') || '';
        if (href.startsWith('http://') || href.startsWith('https://') || href.startsWith('mailto:')) {
          cleanEl.setAttribute('href', href);
          cleanEl.setAttribute('target', '_blank');
          cleanEl.setAttribute('rel', 'noopener noreferrer');
        }
      } else if (tagName === 'span') {
        const color = el.getAttribute('data-note-it-color');
        if (color && HEX_COLOR_REGEX.test(color)) {
          cleanEl.setAttribute('data-note-it-color', color);
          cleanEl.setAttribute('style', `color: ${color}`);
        }
      } else if (tagName === 'mark') {
        const highlight = el.getAttribute('data-note-it-highlight');
        if (highlight && HEX_COLOR_REGEX.test(highlight)) {
          cleanEl.setAttribute('data-note-it-highlight', highlight);
          cleanEl.setAttribute('style', `background-color: ${highlight}`);
        }
      }

      // Recursively sanitize children
      for (const child of Array.from(el.childNodes)) {
        const cleanChild = sanitizeNode(child);
        if (cleanChild) cleanEl.appendChild(cleanChild);
      }

      return cleanEl;
    }

    return null;
  }

  const cleanBody = document.createElement('body');
  for (const child of Array.from(doc.body.childNodes)) {
    const cleanChild = sanitizeNode(child);
    if (cleanChild) cleanBody.appendChild(cleanChild);
  }

  return cleanBody.innerHTML;
}
